### PR TITLE
[CHANGE] use variable $(DOCKER_DEVIMAGE)

### PR DESCRIPTION
**Pull request by lborguetti**
Change simple detail in Makefile!

### CODE REVIEW

**Comment by katcipis** [comment]
Is this request paleo ?

**Comment by katcipis** [comment]
hmm travis is checking if it is paleo :D

**Comment by lborguetti** [comment]
Hum, this request is very lowcarb! :-)

**Comment by i4ki** [comment]
Thanks @lborguetti =)

**Pull request merged**
