### PR TITLE
[CHANGE] Change project structure. Closes #19

### LINKED ISSUE #19: Fix project structure
We should have a more clear structure on the project root, like:

cli
service
lib

Instead of what we have today, it is hard to know where is the lib/service (the cli is pretty obvious :-)

### PR DESCRIPTION
**Pull request by i4ki**

### CODE REVIEW

**Comment by i4ki** [comment]
@katcipis Take a look! 

What do you think?

**Comment by katcipis** [comment]
I think it is great :D. The only problem is why does _make all_ and _make library_ only produces the library directory on the bundles ? Doesn't Go libraries produce a *.a" file ?

**Comment by katcipis** [comment]
The master is also not producing anything inside of bundles... Is this normal ? :P (first Go library lol, I remember reading about a .a file...but Im not sure anymorel)

**Comment by i4ki** [comment]
you are right! I haven't verified that.

using go build -o "$DEST/neosearch.a" should create an archive (ar) file representing the entire package. You can verify with "ar t $DEST/neosearch.a"

I will fix that.

**Comment by i4ki** [comment]
but... What is the relevance of "make library"? Who will use that command?

When you build a library without the "-o" option, the go command tool will generate the ar files inside the $GOPATH/pkg.

I guess that we can drop the option "make library". Do you agree?

**Comment by katcipis** [comment]
I agree to drop _make library_

**Pull request merged**
